version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db


  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=adtelligent_back
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  tabix:
      image: spoonest/clickhouse-tabix-web-client:latest
      container_name: tabix
      ports:
        - "8080:8080"
      environment:
        - CLICKHOUSE_HOST=clickhouse
        - CLICKHOUSE_PORT=8123
        - CLICKHOUSE_USER=default
        - CLICKHOUSE_PASSWORD=mypassword
      depends_on:
        - clickhouse
volumes:
  clickhouse_data:



volumes:
  mongo_data:
  clickhouse_data:
