name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Biome check
        run: npx biome check .

      - name: Type-check & build
        run: npm run build
